import * as types from '../mutation-types'

const state = {
  collapse: false,
  data: [
    {'resourceName': '配置管理',
      'resourceCode': 'configurationManage',
      'hidden': false,
      'icon': 'cogs',
      'children':
      [{'resourceName': 'zookeeper管理',
        'resourceCode': 'zookeeperManage',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': 'mq管理',
        'resourceCode': 'messageQueue',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': 'node管理',
        'resourceCode': 'nodeManage',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': 'agent管理',
        'resourceCode': 'agentManage',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': 'LVS管理',
        'resourceCode': 'lvsManage',
        'hidden': false,
        'icon': 'cog',
        'children': null}]},
    {'resourceName': '迁移计划',
      'resourceCode': 'schedule',
      'hidden': false,
      'icon': 'exchange',
      'children':
      [{'resourceName': '系统迁移计划',
        'resourceCode': 'systemSchedule',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': '数据迁移计划',
        'resourceCode': 'dataSchedule',
        'hidden': false,
        'icon': 'cog',
        'children': null}]},
    {'resourceName': '基础环境同步',
      'resourceCode': 'environmentalParmSync',
      'hidden': false,
      'icon': 'certificate',
      'children':
      [{'resourceName': '基础环境复制',
        'resourceCode': 'baseEnvClone',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': '操作系统参数同步',
        'resourceCode': 'osParmSync',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': '应用软件参数同步',
        'resourceCode': 'softwareParmSync',
        'hidden': false,
        'icon': 'cog',
        'children': null}]},
    {'resourceName': 'SQL数据库同步',
      'resourceCode': 'databaseSynchronization',
      'hidden': false,
      'icon': 'database',
      'children':
      [{'resourceName': '数据源配置',
        'resourceCode': 'dataSourceConfiguration',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': '数据表配置',
        'resourceCode': 'dataTableConfiguration',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': 'MySQL配置',
        'resourceCode': 'canalConfiguration',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': 'Oracle配置',
        'resourceCode': 'yugongConfiguration',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': 'Channel管理',
        'resourceCode': 'channelManage',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': '主备配置',
        'resourceCode': 'dataMatrixConfiguration',
        'hidden': false,
        'icon': 'cog',
        'children': null}]},
    {'resourceName': '文件同步',
      'resourceCode': 'fileSynchronization',
      'hidden': false,
      'icon': 'file',
      'children':
      [{'resourceName': '文件目录配置',
        'resourceCode': 'fileDirectoryConfig',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': '文件同步配置',
        'resourceCode': 'pathSyncConfig',
        'hidden': false,
        'icon': 'cog',
        'children': null}]},
    {'resourceName': 'NoSQL数据库同步',
      'resourceCode': 'sessionSynchronization',
      'hidden': false,
      'icon': 'th',
      'children':
      [{'resourceName': 'Redis配置',
        'resourceCode': 'redisSyncConfig',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': 'Mongodb配置',
        'resourceCode': 'mongodbSyncConfig',
        'hidden': false,
        'icon': 'cog',
        'children': null}]},
    {'resourceName': '流量复制',
      'resourceCode': 'tcpcopy',
      'hidden': false,
      'icon': 'clone',
      'children':
      [{'resourceName': '流量复制配置',
        'resourceCode': 'tcpcopyConfiguration',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': '监控访问时间',
        'resourceCode': 'monitorTime',
        'hidden': false,
        'icon': 'cog',
        'children': null}]},
    {'resourceName': '监控管理',
      'resourceCode': 'monitorManage',
      'hidden': false,
      'icon': 'binoculars',
      'children':
      [{'resourceName': '日志管理',
        'resourceCode': 'logManage',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': '运维监控',
        'resourceCode': 'operationMonitor',
        'hidden': false,
        'icon': 'telegram',
        'children': null},
      {'resourceName': '预警列表',
        'resourceCode': 'alarmList',
        'hidden': false,
        'icon': 'th-list',
        'children': null},
      {'resourceName': '核对监控列表',
        'resourceCode': 'checkMonitorList',
        'hidden': false,
        'icon': 'table',
        'children': null}]},
    {'resourceName': '系统管理',
      'resourceCode': 'systemManage',
      'hidden': false,
      'icon': 'cubes',
      'children':
      [{'resourceName': '权限管理',
        'resourceCode': 'permissionManage',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': '系统初始化',
        'resourceCode': 'systemInitialization',
        'hidden': false,
        'icon': 'cog',
        'children': null},
      {'resourceName': '系统管理',
        'resourceCode': 'systemManage',
        'hidden': false,
        'icon': 'cog',
        'children': null}]}
  ]
  // 取消testDemo模块 , {'resourceName': 'testDemo', 'resourceCode': 'demo', 'icon': 'tumblr', 'children':  [{'resourceName': 'demo', 'resourceCode': 'demo', 'icon': 'cog', 'children': null}, {'resourceName': 'hello', 'resourceCode': 'hello', 'icon': 'cog', 'children': null}, {'resourceName': 'tb', 'resourceCode': 'tb', 'icon': 'cog', 'children': null}]}
}

const actions = {
  toggleCollapse({ commit }) {
    commit(types.MENU_TOGGLE_COLLAPSE)
  },
  setData({ commit }, data) {
    commit(types.MENU_SET_DATA, data.data)
  }
}

const mutations = {
  [types.MENU_TOGGLE_COLLAPSE](state) {
    state.collapse = !state.collapse
  },
  [types.MENU_SET_DATA](state, data) {
    console.log(data)
    state.data = data
  }
}

export default {
  namespaced: true,
  state,
  actions,
  mutations
}
